/* empty css                      */(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();document.querySelectorAll(".faq-acc-el-trigger").forEach(i=>{i.addEventListener("click",()=>{const n=i.closest(".faq-acc-el"),a=n.querySelector(".faq-acc-el-descr-frame"),d=i.querySelector("svg"),e=n.classList.contains("open"),t=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M14 6V22" stroke="#F4A93D" stroke-width="2" stroke-linecap="round" />
  <path d="M22 14L6 14" stroke="#F4A93D" stroke-width="2" stroke-linecap="round" />
</svg>`,c=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M22 14L6 14" stroke="#F4A93D" stroke-width="2" stroke-linecap="round" />
</svg>`;e?(n.classList.remove("open"),a.style.maxHeight="0",d.outerHTML=t):(n.classList.add("open"),a.style.maxHeight=a.scrollHeight+"px",d.outerHTML=c)})});document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),n=i.querySelector(".icon"),a=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M34 30L10 30" stroke="#E8EFF7" stroke-width="2" stroke-linecap="round" />
  <path d="M34 22L10 22" stroke="#E8EFF7" stroke-width="2" stroke-linecap="round" />
  <path d="M34 14L10 14" stroke="#E8EFF7" stroke-width="2" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#E8EFF7" />
</svg>
    `;i.addEventListener("click",()=>{t=!t,n.innerHTML=t?o:c,t?s():r()}),d.forEach(u=>u.addEventListener("click",()=>{r(),n.innerHTML=c,t=!1})),window.addEventListener("scroll",l);function s(){a.style.display="block"}function r(){a.style.display="none"}function l(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const s=document.getElementById(o);if(!s)return;const r=i(),l=s.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:l,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(s){const r=this.getAttribute("href");if(!r)return;const[l,u]=r.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(l===""||l==="./"||l===f||l==="./"+f)||!document.getElementById(u)||(s.preventDefault(),n(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(r=>r.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${o}"]`);s&&s.closest(".navigation-item").classList.add("active")}function c(){const o=window.pageYOffset+i()+100;d.forEach(s=>{const r=s.offsetTop,l=r+s.offsetHeight;o>=r&&o<l&&t(s.id)})}if(window.addEventListener("scroll",c),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
